cmake_minimum_required(VERSION 3.8)

include(CPackConfig.cmake)

macro(set_ name value)
  if(NOT DEFINED "${name}")
    set("${name}" "${value}")
  endif()
endmacro()

set_(CPACK_PACKAGE_CONTACT "example <example@example.com>")
set_(CPACK_STRIP_FILES YES)
set_(CPACK_INSTALL_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/pre_build.cmake")

set(CPACK_COMPONENTS_EXAMPLE_RUNTIME example_Runtime)
set(CPACK_COMPONENTS_EXAMPLE_DEVELOPMENT example_Development)

set_(CPACK_DEB_COMPONENT_INSTALL YES)

set_(
    CPACK_DEBIAN_EXAMPLE_RUNTIME_PACKAGE_NAME
    "libexample${CPACK_PACKAGE_VERSION_MAJOR}"
)
set_(
    CPACK_DEBIAN_EXAMPLE_DEVELOPMENT_PACKAGE_NAME
    "libexample${CPACK_PACKAGE_VERSION_MAJOR}-dev"
)

set_(CPACK_DEBIAN_EXAMPLE_RUNTIME_FILE_NAME DEB-DEFAULT)
set_(CPACK_DEBIAN_EXAMPLE_DEVELOPMENT_FILE_NAME DEB-DEFAULT)

# unset(CPACK_DEBIAN_PACKAGE_EPOCH)
set_(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
# unset(CPACK_DEBIAN_PACKAGE_RELEASE)

# unset(CPACK_DEBIAN_PACKAGE_ARCHITECTURE)

set_(CPACK_DEBIAN_PACKAGE_DEPENDS "")

set_(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS YES)

# unset(CPACK_DEBIAN_PACKAGE_MAINTAINER)

unset(CPACK_DEBIAN_EXAMPLE_RUNTIME_DESCRIPTION)
unset(CPACK_DEBIAN_EXAMPLE_DEVELOPMENT_DESCRIPTION)

set_(CPACK_DEBIAN_EXAMPLE_RUNTIME_PACKAGE_SECTION libs)
set_(CPACK_DEBIAN_EXAMPLE_DEVELOPMENT_PACKAGE_SECTION libdevel)

unset(CPACK_DEBIAN_ARCHIVE_TYPE)

set_(CPACK_DEBIAN_COMPRESSION_TYPE gzip)

set(CPACK_DEBIAN_PACKAGE_PRIORITY optional)

# unset(CPACK_DEBIAN_PACKAGE_HOMEPAGE)

set_(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

# unset(CPACK_DEBIAN_PACKAGE_DEBUG)

# unset(CPACK_DEBIAN_PACKAGE_PREDEPENDS)
# unset(CPACK_DEBIAN_PACKAGE_ENHANCES)
# unset(CPACK_DEBIAN_PACKAGE_BREAKS)
# unset(CPACK_DEBIAN_PACKAGE_CONFLICTS)
# unset(CPACK_DEBIAN_PACKAGE_PROVIDES)
# unset(CPACK_DEBIAN_PACKAGE_REPLACES)
# unset(CPACK_DEBIAN_PACKAGE_RECOMMENDS)
# unset(CPACK_DEBIAN_PACKAGE_SUGGESTS)

set_(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS YES)
set_(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY "=")

# unset(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA)
set_(
    CPACK_DEBIAN_EXAMPLE_RUNTIME_PACKAGE_CONTROL_EXTRA
    "${CMAKE_CURRENT_LIST_DIR}/triggers"
)
set_(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION YES)

# unset(CPACK_DEBIAN_PACKAGE_SOURCE)

# unset(CPACK_DEBIAN_DEBUGINFO_PACKAGE)

# HACK: CPack will install postinst and postrm scripts, which call ldconfig and
# lintian emits a warning for that. To use triggers alone, this variable can be
# set to this list of values to disable generating the files. This variable is
# an internal implementation detail of CPackDeb.cmake module loaded by CPack.
set(PACKAGE_CONTROL_EXTRA postinst postrm)
