name: Continuous Integration

on:
  push:
    branches:
      - master
      - cmake-3.12
      - cmake-3.8

  pull_request:
    branches:
      - master
      - cmake-3.12
      - cmake-3.8

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        type: [shared, static]

        os: [macos, ubuntu, windows]

        include:
          - { type: shared, build: YES }
          - { type: static, build: NO }

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
          -D BUILD_SHARED_LIBS=${{ matrix.build }}

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --config Release --prefix prefix

      - name: Test
        working-directory: build
        run: ctest -C Release
